# Generated by Django 4.1.5 on 2024-03-22 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='Оценка'),
        ),
    ]
