# Generated by Django 4.1.5 on 2024-09-26 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todo_mobile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Чеклист',
                'verbose_name_plural': 'Чеклисты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=400, verbose_name='Работы')),
                ('unit', models.CharField(max_length=400, verbose_name='Единицы измерения')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo_mobile.checklist')),
            ],
            options={
                'verbose_name': 'Запись чеклиста',
                'verbose_name_plural': 'Записи чеклиста',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название задачи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('related_place', models.CharField(max_length=400, verbose_name='Связанное место')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес точки')),
                ('activity', models.IntegerField(verbose_name='Мероприятие')),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CheckListItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=todo_mobile.models.image_path, verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('check_list_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo_mobile.checklistitem')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo_mobile.task'),
        ),
    ]
