# Generated by Django 4.1.5 on 2024-02-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Входящая открытка')),
                ('image', models.ImageField(upload_to='images', verbose_name='лицевая сторона')),
                ('sender', models.CharField(max_length=50, verbose_name='имя отправителя')),
                ('country', models.CharField(max_length=50, verbose_name='страна отправления')),
                ('travel_time', models.IntegerField(max_length=30, verbose_name='дней в пути')),
            ],
        ),
    ]
