# Generated by Django 4.1.5 on 2024-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0002_remove_postcard_title_alter_postcard_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='library', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Открытка для отправления',
                'verbose_name_plural': 'Открытки для отправления',
            },
        ),
        migrations.AlterModelOptions(
            name='postcard',
            options={'verbose_name': 'Полученная открытка', 'verbose_name_plural': 'Полученные открытки'},
        ),
    ]
