# Generated by Django 4.1.5 on 2024-02-28 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0003_library_alter_postcard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='date_receiving',
            field=models.DateField(default=datetime.date(2024, 2, 28), verbose_name='дата получения открытки'),
        ),
    ]
