# Generated by Django 4.1.4 on 2022-12-26 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название модели', models.CharField(max_length=500)),
                ('Статус', models.CharField(choices=[('washed', 'Лежит в магазине'), ('in_inventory', 'Куплено'), ('assembling', 'Собирается'), ('priming', 'Грунтуется'), ('battle_ready_painting', 'Крашу в базу'), ('parade_ready_painting', 'Хайлайтю'), ('base_decorating', 'Оформляю поставку'), ('varnishing', 'Задуваю лаком'), ('done', 'Закончено')], default='washed', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Описание выполненной работы', models.CharField(max_length=500)),
                ('Подробности выполнененной работы', models.TextField()),
                ('Дата записи', models.DateTimeField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Прогресс', to='work_in_progress.model')),
            ],
        ),
    ]
