# Generated by Django 4.1.4 on 2022-12-27 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название модели')),
                ('status', models.CharField(choices=[('washed', 'Лежит в магазине'), ('in_inventory', 'Куплено'), ('assembling', 'Собирается'), ('priming', 'Грунтуется'), ('battle_ready_painting', 'Крашу в базу'), ('parade_ready_painting', 'Хайлайтю'), ('base_decorating', 'Оформляю поставку'), ('varnishing', 'Задуваю лаком'), ('done', 'Закончено')], default='washed', max_length=200, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ModelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Описание выполненной работы')),
                ('description', models.TextField(verbose_name='Подробности выполнененной работы')),
                ('datetime', models.DateTimeField(verbose_name='Дата записи')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.model', verbose_name='Прогресс')),
            ],
        ),
    ]
