# Generated by Django 4.1.5 on 2023-01-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0002_bsunit_alter_model_status_alter_modelprogress_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('source', models.CharField(max_length=500, verbose_name='Источник')),
            ],
        ),
        migrations.AddField(
            model_name='modelprogress',
            name='time',
            field=models.FloatField(default=0.0, verbose_name='Затраченое время'),
        ),
        migrations.AddField(
            model_name='bsunit',
            name='bs_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.bscategory', verbose_name='Тип'),
        ),
    ]
