# Generated by Django 4.1.5 on 2023-01-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0003_bscategory_modelprogress_time_bsunit_bs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='battlescribe_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.bsunit', verbose_name='Из каталога BS'),
        ),
        migrations.AlterField(
            model_name='modelprogress',
            name='time',
            field=models.FloatField(default=0.0, verbose_name='Затраченое время в часах'),
        ),
    ]
