# Generated by Django 4.1.5 on 2023-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0004_model_battlescribe_unit_alter_modelprogress_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bscategory',
            options={'verbose_name': 'Категория BattleScribe', 'verbose_name_plural': 'Категории BattleScribe'},
        ),
        migrations.AlterModelOptions(
            name='bsunit',
            options={'verbose_name': 'Юнит BattleScribe', 'verbose_name_plural': 'Юниты BattleScribe'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель в работе', 'verbose_name_plural': 'Модели в работе'},
        ),
        migrations.AlterModelOptions(
            name='modelprogress',
            options={'verbose_name': 'Работа над моделью', 'verbose_name_plural': 'Работы над моделью'},
        ),
        migrations.AddField(
            model_name='model',
            name='buy_date',
            field=models.DateTimeField(null=True, verbose_name='Дата покупки'),
        ),
    ]
