# Generated by Django 4.1.5 on 2023-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0007_modelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто'),
        ),
    ]
