# Generated by Django 4.1.5 on 2023-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0010_modelimage_created_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='telegram_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ник в телеге'),
        ),
    ]
