# Generated by Django 4.1.5 on 2024-02-21 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_in_progress', '0011_alter_artist_telegram_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название краски')),
                ('type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тип краски')),
                ('details', models.CharField(blank=True, max_length=600, null=True, verbose_name='Доп инфо')),
                ('color', models.CharField(blank=True, max_length=25, null=True, verbose_name='Шеснадцатеричное RGB представление цвета')),
            ],
            options={
                'verbose_name': 'Краска',
                'verbose_name_plural': 'Краски',
            },
        ),
        migrations.CreateModel(
            name='PaintVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Вендор краски',
                'verbose_name_plural': 'Вендоры красок',
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Красильщик', 'verbose_name_plural': 'Красильщики'},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={'verbose_name': 'Изображение модели', 'verbose_name_plural': 'Изображения модели'},
        ),
        migrations.AddField(
            model_name='model',
            name='unit_count',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Количество миниатюр'),
        ),
        migrations.CreateModel(
            name='PaintInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.BooleanField(default=False, verbose_name='Нужна')),
                ('has', models.BooleanField(default=False, verbose_name='Есть')),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.paint', verbose_name='Краска')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запас красок',
                'verbose_name_plural': 'Запасы красок',
            },
        ),
        migrations.AddField(
            model_name='paint',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_in_progress.paintvendor', verbose_name='Производитель краски'),
        ),
    ]
