# Generated by Django 4.1.5 on 2024-02-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0012_paint_paintvendor_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Истребительная команда',
                'verbose_name_plural': 'Истребительная команда',
            },
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name'], 'verbose_name': 'Модель в работе', 'verbose_name_plural': 'Модели в работе'},
        ),
        migrations.AlterModelOptions(
            name='modelprogress',
            options={'ordering': ['datetime'], 'verbose_name': 'Работа над моделью', 'verbose_name_plural': 'Работы над моделью'},
        ),
        migrations.AlterModelOptions(
            name='paint',
            options={'ordering': ['vendor__name', 'type', 'name'], 'verbose_name': 'Краска', 'verbose_name_plural': 'Краски'},
        ),
        migrations.AlterModelOptions(
            name='paintinventory',
            options={'ordering': ['user', 'has'], 'verbose_name': 'Запас красок', 'verbose_name_plural': 'Запасы красок'},
        ),
        migrations.AddField(
            model_name='model',
            name='terrain',
            field=models.BooleanField(default=False, verbose_name='Террейн'),
        ),
        migrations.AlterField(
            model_name='modelprogress',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='progress', to='work_in_progress.model', verbose_name='Прогресс'),
        ),
        migrations.CreateModel(
            name='Operative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('kill_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.killteam', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Оперативник',
                'verbose_name_plural': 'Оперативники',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='kill_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.killteam', verbose_name='KillTeam каталога BS'),
        ),
    ]
