# Generated by Django 4.1.5 on 2024-02-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0013_killteam_alter_model_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operative',
            new_name='KillTeamOperative',
        ),
    ]
