# Generated by Django 4.1.5 on 2024-04-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_in_progress', '0014_rename_operative_killteamoperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintinventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
