# Generated by Django 4.1.5 on 2024-10-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_in_progress', '0015_alter_paintinventory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская группа статусов',
                'verbose_name_plural': 'Пользовательские группы статусов',
            },
        ),
        migrations.AlterModelOptions(
            name='paint',
            options={'ordering': ['vendor__name', 'type', 'details', 'name'], 'verbose_name': 'Краска', 'verbose_name_plural': 'Краски'},
        ),
        migrations.CreateModel(
            name='UserModelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('is_initial', models.BooleanField(verbose_name='Является начальным')),
                ('is_final', models.BooleanField(verbose_name='Является последним')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='work_in_progress.statusgroup', verbose_name='Группа')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pevious_status', to='work_in_progress.usermodelstatus', verbose_name='Предыдущий статус')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='next_status', to='work_in_progress.usermodelstatus', verbose_name='Следующий статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательский статус',
                'verbose_name_plural': 'Пользовательские статусы',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='model_status', to='work_in_progress.usermodelstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='modelprogress',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='progress_status', to='work_in_progress.usermodelstatus', verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='usermodelstatus',
            constraint=models.UniqueConstraint(fields=('user_id', 'is_initial'), name='uniq_initial_status_per_user'),
        ),
        migrations.AddConstraint(
            model_name='usermodelstatus',
            constraint=models.UniqueConstraint(fields=('user_id', 'is_final'), name='uniq_final_status_per_user'),
        ),
    ]
