# Generated by Django 4.1.5 on 2024-10-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0016_statusgroup_alter_paint_options_usermodelstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelstatus',
            name='slug',
            field=models.CharField(default='test', max_length=500, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodelstatus',
            name='transition_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок в прогрессе модели при переходе в статус'),
        ),
        migrations.AlterField(
            model_name='usermodelstatus',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='previous_status', to='work_in_progress.usermodelstatus', verbose_name='Предыдущий статус'),
        ),
    ]
