# Generated by Django 4.1.5 on 2024-10-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0018_remove_usermodelstatus_uniq_initial_status_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelstatus',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='work_in_progress.statusgroup', verbose_name='Группа'),
        ),
    ]
