# Generated by Django 4.1.5 on 2024-10-21 15:12

from django.db import migrations
from work_in_progress.models import Model as _Model


def add_statuses(apps, schema_editor):
    UserModelStatus = apps.get_model("work_in_progress", "UserModelStatus")
    User = apps.get_model("auth", "User")

    ordered_statuses = [k.value for k in _Model.Status.work_order()]

    stages_by_status = {k.value: v for k, v in _Model.stages()}
    status_name_by_status = {k: v for k, v in zip(_Model.Status.values, _Model.Status.labels)}
    users = User.objects.all()
    count = len(ordered_statuses)
    status_model_by_status = {}
    for user in users:
        for i, status in enumerate(ordered_statuses):
            transition_title = stages_by_status[status] if status in stages_by_status else ""
            is_initial = i == 0
            is_final = i == count - 1
            new_user_status = UserModelStatus(user=user,
                                              name=status_name_by_status[status],
                                              slug=status,
                                              transition_title=transition_title,
                                              is_initial=is_initial,
                                              is_final=is_final)
            new_user_status.save()
            status_model_by_status[status] = new_user_status

        for i, status in enumerate(ordered_statuses):
            status_model = status_model_by_status[status]
            if i < count - 1:
                next_status = ordered_statuses[i + 1]
                status_model.next = status_model_by_status[next_status]
            if i > 0:
                prev_status = ordered_statuses[i - 1]
                status_model.previous = status_model_by_status[prev_status]
            status_model.save()


def backwards(apps, schema_editor):
    UserModelStatus = apps.get_model("work_in_progress", "UserModelStatus")
    UserModelStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0019_alter_usermodelstatus_group'),
    ]

    operations = [
        migrations.RunPython(add_statuses, backwards),
    ]
