# Generated by Django 4.1.5 on 2024-10-21 16:16

from django.db import migrations


def forward(apps, schema_editor):
    Model = apps.get_model("work_in_progress", "Model")
    ModelProgress = apps.get_model("work_in_progress", "ModelProgress")
    UserModelStatus = apps.get_model("work_in_progress", "UserModelStatus")
    User = apps.get_model("auth", "User")
    users = User.objects.all()
    for user in users:
        user_models = Model.objects.filter(user=user)
        user_statues_by_slug = {r.slug: r for r in UserModelStatus.objects.filter(user=user)}
        for model in user_models:
            if model.status is not None:
                user_model_status = user_statues_by_slug[model.status]
                model.user_status = user_model_status
                model.save()

        user_progress = ModelProgress.objects.filter(model__user=user)
        for progress in user_progress:
            if progress.status is not None:
                user_model_status = user_statues_by_slug[progress.status]
                progress.user_status = user_model_status
                progress.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0020_fill_user_statuses_from_enum'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
