# Generated by Django 4.1.5 on 2024-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0021_fill_user_status_in_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelstatus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
