# Generated by Django 4.1.5 on 2024-10-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0022_usermodelstatus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusgroup',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Пользовательская группа статусов', 'verbose_name_plural': 'Пользовательские группы статусов'},
        ),
        migrations.AlterModelOptions(
            name='usermodelstatus',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Пользовательский статус', 'verbose_name_plural': 'Пользовательские статусы'},
        ),
        migrations.AddField(
            model_name='statusgroup',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='usermodelstatus',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='previous_status', to='work_in_progress.usermodelstatus', verbose_name='Следующий статус'),
        ),
        migrations.AlterField(
            model_name='usermodelstatus',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='next_status', to='work_in_progress.usermodelstatus', verbose_name='Предыдущий статус'),
        ),
    ]
