# Generated by Django 4.1.5 on 2024-11-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0023_alter_statusgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='work_in_progress.statusgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='usermodelstatus',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='previous_status', to='work_in_progress.usermodelstatus', verbose_name='Следующий статус'),
        ),
        migrations.AlterField(
            model_name='usermodelstatus',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='next_status', to='work_in_progress.usermodelstatus', verbose_name='Предыдущий статус'),
        ),
    ]
