# Generated by Django 4.1.5 on 2024-11-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_in_progress', '0024_alter_usermodelstatus_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='battlescribe_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.bsunit', verbose_name='Из каталога BS'),
        ),
        migrations.AlterField(
            model_name='model',
            name='kill_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_in_progress.killteam', verbose_name='KillTeam каталога BS'),
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Группа моделей',
                'verbose_name_plural': 'Группы моделей',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='model',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='model_group', to='work_in_progress.modelgroup', verbose_name='Группа'),
        ),
    ]
