# Generated by Django 4.1.5 on 2024-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0025_alter_model_battlescribe_unit_alter_model_kill_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='group',
        ),
        migrations.AddField(
            model_name='model',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='model_group', to='work_in_progress.modelgroup', verbose_name='Группа'),
        ),
    ]
