# Generated by Django 4.1.5 on 2024-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0026_remove_model_group_model_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='group',
            field=models.ManyToManyField(related_name='model_group', to='work_in_progress.modelgroup', verbose_name='Группа'),
        ),
    ]
