# Generated by Django 4.1.5 on 2024-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_in_progress', '0027_alter_model_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='group',
        ),
        migrations.AddField(
            model_name='model',
            name='groups',
            field=models.ManyToManyField(related_name='model_group', to='work_in_progress.modelgroup', verbose_name='Группы'),
        ),
    ]
